theme: jekyll-theme-cayman
title: Pedro Azeredo Paix√£o
comments: true
description: Serial Entrepeneur, Software Developer and Startup Enthusiast; MSc Informatics and Computing Engineering @ FEUP
excerpt_separator: "<!-- more -->"
permalink: /:title/

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: zepedropaixao@gmail.com
  facebook:
  flickr:
  github: zepedropaixao
  instagram:
  linkedin: zepedropaixao
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: zepedropaixao
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/ 

linkedin: zepedropaixao

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed
